### PR TITLE
Start on Simplifying Save Process and Fix "segment" Capitialization Error

### PR DESCRIPTION
**Pull request by knot126**
Changes in this PR:

- A temporary fix for the "segment" tag being capitalised. (Maybe someone knows a better way to do this?)
- Started to simplify the save process by not worrying if the value is floating point or not. (Smash Hit will accept either one.)

Note: This is my first PR, please point out any issues.

### CODE REVIEW

**Comment by Skinnerpuma737** [comment]
Hi knot. just thought i would point out that the class Segment in Segment.cs does not matter if it is capitalized as that is what the bit in the data.cs does. the bit which you fixed.

the segment captialization error is what caused it to be capital not the class name

**Comment by Skinnerpuma737** [comment]
Segment.cs's class should be a capital. if you change it to lowercase it will also cause errors elsewhere in the code as i have defined it in other places.

**Comment by knot126** [comment]
I've pushed a commit to revert that part, but now it seems it's showing as `Segment` again. Does this still happen for you?

**Comment by Skinnerpuma737** [comment]
wdym does this still happen for you?

**Comment by knot126** [comment]
Is the main segment tag being capitalised?

**Comment by Skinnerpuma737** [comment]
i will test it.

**Comment by Skinnerpuma737** [comment]
yes it is i am going to work on a fix for it that isnt renaming the class. it seems to be a bug with the xml package

**Comment by Skinnerpuma737** [comment]
i fixed it

**Comment by knot126** [comment]
Thanks!

**Pull request merged**
